### ISSUE TITLE
Partial Read/Write Exception

### ISSUE THREAD

**Issue by accolad3** [Dewera/Lunar#25]
```
Unhandled exception. System.ComponentModel.Win32Exception (299): Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Lunar.FileResolution.FileResolver.ResolveFilePath(ActivationContext activationContext, String fileName) in C:\Users\Me\source\repos\Lunar\Lunar\FileResolution\FileResolver.cs:line 27
   at Lunar.LibraryMapper.LoadDependencies() in C:\Users\Me\source\repos\Lunar\Lunar\LibraryMapper.cs:line 464
   at Lunar.LibraryMapper.MapLibrary() in C:\Users\Me\source\repos\Lunar\Lunar\LibraryMapper.cs:line 118
   at Specter.Program.Main(String[] args) in C:\Users\Me\source\repos\I\S\Program.cs:line 18
```

**Comment by Dewera** [comment]
That's an issue originating from accessing this [property](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.mainmodule?view=net-5.0). Unfortunately as the property is part of the official SDK, there is nothing I can do about it. If the issue persists I'd recommend you open an issue on the official [dotnet/runtime](https://github.com/dotnet/runtime) repo, although it's likely an internal OS issue.
